services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - venv:/home/vscode/.venv
      - ../config.ini:/home/vscode/.gamdl/config.ini
    tty: true
    stdin_open: true

  wrapper:
    image: tkgling/wrapper:23
    volumes:
      - ../rootfs/data:/app/rootfs/data
    environment:
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  venv:
